#!/usr/bin/env tsx
/**
 * Persists today's brief into src/lib/data/briefs.ts so dated permalinks render
 * real history. Run after `npm run sync` (the snapshot must be current first).
 *
 *   npm run sync && npm run persist-brief
 *
 * Idempotent: replaces an existing entry for today's slug, else appends.
 * Keeps the most recent N entries to bound the file size.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { serializeBrief } from "../src/lib/brief";

const __filename = fileURLToPath(import.meta.url);
const ROOT = resolve(dirname(__filename), "..");
const FILE = resolve(ROOT, "src/lib/data/briefs.ts");
const KEEP = 400; // ~13 months of daily briefs

async function main() {
  const today = serializeBrief();

  // Read existing entries out of the generated module (between the [ and ]).
  let existing: Array<{ slug: string }> = [];
  try {
    const src = await readFile(FILE, "utf8");
    const m = src.match(/STORED_BRIEFS:\s*StoredBrief\[\]\s*=\s*(\[[\s\S]*\]);/);
    if (m) existing = JSON.parse(m[1]);
  } catch {
    // first run — start empty
  }

  const map = new Map(existing.map((b) => [b.slug, b]));
  map.set(today.slug, today); // replace or add today
  const all = [...map.values()]
    .sort((a, b) => (a.slug < b.slug ? 1 : -1)) // newest first
    .slice(0, KEEP);

  const out = `// AUTO-GENERATED by the daily sync (scripts/persist-brief.ts).
// Each entry is a self-contained snapshot of that day's brief, so dated
// permalinks render real history rather than today's live data.
// New days are appended; do not edit by hand.
import type { StoredBrief } from "../brief";

export const STORED_BRIEFS: StoredBrief[] = ${JSON.stringify(all, null, 2)};
`;
  await writeFile(FILE, out, "utf8");
  console.log(`✓ Persisted brief ${today.slug} (${all.length} total in archive)`);
}

main().catch((e) => {
  console.warn(`! persist-brief failed (non-fatal): ${(e as Error).message}`);
});
