#!/usr/bin/env tsx
/**
 * Persists today's SENT Daily Brief V2 edition into
 * src/lib/data/briefV2Editions.ts — the permanent record of what was actually
 * emailed (subject, verdict class, story shape, exact plain-text body) and
 * the subject-freshness memory for briefIntel. Run after `npm run sync`.
 *
 * DBV2-C: the legacy Edition store (src/lib/data/editions.ts) is FROZEN at
 * the cutover — its history is preserved verbatim and its pages keep
 * rendering it, but no new legacy editions are written because that email
 * product is no longer sent. Idempotent per slug; append-only across days.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { briefIntel } from "../src/lib/briefIntel";
import { briefEmailV2Text } from "../src/lib/briefEmailV2";
import type { BriefV2Edition } from "../src/lib/briefV2Archive";

const __filename = fileURLToPath(import.meta.url);
const ROOT = resolve(dirname(__filename), "..");
const FILE = resolve(ROOT, "src/lib/data/briefV2Editions.ts");
const KEEP = 4000; // ~11 years of daily editions

async function main() {
  const b = briefIntel();
  const today: BriefV2Edition = {
    slug: b.asOf,
    subject: b.subject,
    activity: b.verdict.activity,
    storyKind: b.story.kind,
    text: briefEmailV2Text(),
    version: b.version,
  };

  let existing: BriefV2Edition[] = [];
  try {
    const src = await readFile(FILE, "utf8");
    const m = src.match(/BRIEF_V2_EDITIONS:\s*BriefV2Edition\[\]\s*=\s*(\[[\s\S]*\]);/);
    if (m) existing = JSON.parse(m[1]);
  } catch {
    // first run — start empty
  }

  const map = new Map(existing.map((e) => [e.slug, e]));
  map.set(today.slug, today); // replace or add today
  const all = [...map.values()].sort((a, b2) => (a.slug < b2.slug ? 1 : -1)).slice(0, KEEP);

  const out = `// AUTO-GENERATED by the daily sync (scripts/persist-edition.ts).
// Each entry is a permanent, frozen record of a sent Daily Brief V2 edition —
// the subject, verdict class, story shape and the exact plain-text body. New
// editions are appended by the sync; do not edit by hand.
import type { BriefV2Edition } from "../briefV2Archive";

export const BRIEF_V2_EDITIONS: BriefV2Edition[] = ${JSON.stringify(all, null, 2)};
`;
  await writeFile(FILE, out, "utf8");
  console.log(`\u2713 Persisted Daily Brief V2 edition ${today.slug} (${today.activity} \u00b7 ${today.storyKind}; ${all.length} total)`);
}

main().catch((e) => {
  console.warn(`! persist-edition failed (non-fatal): ${(e as Error).message}`);
});
