#!/usr/bin/env tsx
/**
 * Persists today's edition into src/lib/data/editions.ts so the Morning Research
 * Library has a permanent, frozen record of every Daily Research Brief.
 * Run after `npm run sync` (the snapshot must be current first).
 *
 *   npm run sync && npm run persist-edition
 *
 * Idempotent: replaces an existing entry for today's edition number, else
 * appends. Append-only across days — past editions are never altered.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { editionContent } from "../src/lib/emailBrief";
import type { Edition } from "../src/lib/research";

const __filename = fileURLToPath(import.meta.url);
const ROOT = resolve(dirname(__filename), "..");
const FILE = resolve(ROOT, "src/lib/data/editions.ts");
const KEEP = 4000; // ~11 years of daily editions

async function main() {
  const today = editionContent();

  let existing: Edition[] = [];
  try {
    const src = await readFile(FILE, "utf8");
    const m = src.match(/EDITIONS:\s*Edition\[\]\s*=\s*(\[[\s\S]*\]);/);
    if (m) existing = JSON.parse(m[1]);
  } catch {
    // first run — start empty
  }

  const map = new Map(existing.map((e) => [e.edition, e]));
  map.set(today.edition, today); // replace or add today
  const all = [...map.values()].sort((a, b) => b.edition - a.edition).slice(0, KEEP);

  const out = `// AUTO-GENERATED by the daily sync (scripts/persist-edition.ts).
// Each entry is a permanent, self-contained snapshot of that day's Daily
// Research Brief, so /research/<n> renders the exact market conditions from that
// morning — forever. New editions are appended; do not edit by hand.
import type { Edition } from "../research";

export const EDITIONS: Edition[] = ${JSON.stringify(all, null, 2)};
`;
  await writeFile(FILE, out, "utf8");
  console.log(`✓ Persisted edition #${today.edition} (${all.length} total in library)`);
}

main().catch((e) => {
  console.warn(`! persist-edition failed (non-fatal): ${(e as Error).message}`);
});
