#!/usr/bin/env tsx
/**
 * Persists this week's report into src/lib/data/weeklies.ts. Run after the daily
 * sync. Idempotent per ISO week: the current week is refreshed each run and
 * frozen once it passes. Append-only across weeks.
 *
 *   npm run sync && npm run persist-weekly
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { weeklyContent } from "../src/lib/weekly";
import type { WeeklyReport } from "../src/lib/weekly";

const __filename = fileURLToPath(import.meta.url);
const ROOT = resolve(dirname(__filename), "..");
const FILE = resolve(ROOT, "src/lib/data/weeklies.ts");
const KEEP = 600; // ~11 years of weeklies

async function main() {
  const thisWeek = weeklyContent();

  let existing: WeeklyReport[] = [];
  try {
    const src = await readFile(FILE, "utf8");
    const m = src.match(/WEEKLIES:\s*WeeklyReport\[\]\s*=\s*(\[[\s\S]*\]);/);
    if (m) existing = JSON.parse(m[1]);
  } catch {
    // first run — start empty
  }

  const map = new Map(existing.map((w) => [w.slug, w]));
  map.set(thisWeek.slug, thisWeek); // refresh or add this week
  const all = [...map.values()].sort((a, b) => (a.slug < b.slug ? 1 : -1)).slice(0, KEEP);

  const out = `// AUTO-GENERATED by the daily sync (scripts/persist-weekly.ts).
// Each entry is a permanent, self-contained snapshot of that week's HalvingLens
// Weekly Research, keyed by ISO week. The current week is refreshed each run and
// frozen once the week passes. Do not edit by hand.
import type { WeeklyReport } from "../weekly";

export const WEEKLIES: WeeklyReport[] = ${JSON.stringify(all, null, 2)};
`;
  await writeFile(FILE, out, "utf8");
  console.log(`✓ Persisted weekly ${thisWeek.slug} (${all.length} total)`);
}

main().catch((e) => {
  console.warn(`! persist-weekly failed (non-fatal): ${(e as Error).message}`);
});
