// AUTO-GENERATED by the daily sync (scripts/persist-edition.ts).
// Each entry is a permanent, frozen record of a sent Daily Brief V2 edition —
// the subject, verdict class, story shape and the exact plain-text body. New
// editions are appended by the sync; do not edit by hand.
import type { BriefV2Edition } from "../briefV2Archive";

export const BRIEF_V2_EDITIONS: BriefV2Edition[] = [];
