// AUTO-GENERATED by the daily sync (scripts/persist-edition.ts).
// Each entry is a permanent, frozen record of a sent Daily Brief V2 edition —
// the subject, verdict class, story shape and the exact plain-text body. New
// editions are appended by the sync; do not edit by hand.
import type { BriefV2Edition } from "../briefV2Archive";

export const BRIEF_V2_EDITIONS: BriefV2Edition[] = [
  {
    "slug": "2026-08-15",
    "subject": "RHODL Ratio just made an unusual move",
    "activity": "active",
    "storyKind": "mover",
    "text": "HALVINGLENS DAILY BRIEF — 15 Aug 2026\n\nTHE VERDICT: Active week. 14 of 15 monitored readings held within their own ordinary 7-day ranges — 1 moved materially.\n\nSOMETHING CHANGED: RHODL Ratio — −32.5% in 7 days · Unusual.\nA larger 7-day move than most in its own record. Larger than 84% of 7-day moves · 1,474 observations since Jul 2022.\nNow 713 · Deep value · −37.0% over 30 days.\n\nALSO TODAY: ETF demand: 3 straight trading days of net outflows. Net −$162.18M over the past 7 trading days.\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 24/100 · weekly · since 4 Jul 2026\n· Sentiment: Fear · 34/100 · since 15 Jul 2026\n· ETF demand: 3-day outflow streak · −$162.18M over 7 trading days · as of 14 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  }
];
