// AUTO-GENERATED by the daily sync (scripts/persist-edition.ts).
// Each entry is a permanent, frozen record of a sent Daily Brief V2 edition —
// the subject, verdict class, story shape and the exact plain-text body. New
// editions are appended by the sync; do not edit by hand.
import type { BriefV2Edition } from "../briefV2Archive";

export const BRIEF_V2_EDITIONS: BriefV2Edition[] = [
  {
    "slug": "2026-09-01",
    "subject": "A top-5% move in Fear & Greed",
    "activity": "active",
    "storyKind": "historical_extreme",
    "text": "HALVINGLENS DAILY BRIEF — 1 Sep 2026\nBTC $78,534 · +1.1% since yesterday's 08:00 London snapshot\n\nTHE VERDICT: Fear & Greed just made a top-5% 30-day move for its own record. Crowd enthusiasm is heating up while the accumulation window remains open.\n14 of 15 monitored readings held within their own ordinary 7-day ranges — 1 moved materially.\n\nA TOP-5% MOVE FOR ITS OWN RECORD: Fear & Greed just made a top-5% 30-day move for its own record.\n+42 points — Larger than 95% of 30-day moves · 3,101 observations since Feb 2018.\nFear & Greed moved from Fear to Greed.\nNow 69 · Greed.\nWindow: 30 days · as of 1 Sep 2026\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 35/100 · weekly · since 4 Jul 2026\n· Sentiment: Greed · 69/100 · since 20 Aug 2026\n· ETF demand: 1-day inflow streak · +$1.45B over 7 trading days · as of 31 Aug 2026\n\nSee Fear & Greed in full context → https://halvinglens.com/cycle-dashboard#dashboard-market-board\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-edition-v1"
  },
  {
    "slug": "2026-08-31",
    "subject": "A quiet day for the 15 monitored readings",
    "activity": "active",
    "storyKind": "quiet",
    "text": "HALVINGLENS DAILY BRIEF — 31 Aug 2026\nBTC $77,689 · −0.7% since yesterday's 08:00 London snapshot\n\nTHE VERDICT: Little changed across the 15 monitored readings today. Crowd enthusiasm is heating up while the accumulation window remains open.\n12 of 15 monitored readings held within their own ordinary 7-day ranges — 3 moved materially.\n\nA QUIET DAY: No reading crossed a state boundary, made a top-5% move for its own record, or extended a notable streak today.\nStable readings are information: every standing state below keeps counting, and the day's calm is measured against each reading's own history, not a feeling.\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 35/100 · weekly · since 4 Jul 2026\n· Sentiment: Greed · 62/100 · since 20 Aug 2026\n· ETF demand: 1-day outflow streak · +$1.84B over 7 trading days · as of 28 Aug 2026\n\nSee all 15 signals holding steady → https://halvinglens.com/cycle-dashboard#dashboard-market-board\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-edition-v1"
  },
  {
    "slug": "2026-08-30",
    "subject": "A top-5% move in Fear & Greed",
    "activity": "mostly_quiet",
    "storyKind": "historical_extreme",
    "text": "HALVINGLENS DAILY BRIEF — 30 Aug 2026\nBTC $78,244 · +0.7% since yesterday's 08:00 London snapshot\n\nTHE VERDICT: Fear & Greed just made a top-5% 30-day move for its own record. Crowd enthusiasm is heating up while the accumulation window remains open.\n13 of 15 monitored readings held within their own ordinary 7-day ranges — 2 moved materially.\n\nA TOP-5% MOVE FOR ITS OWN RECORD: Fear & Greed just made a top-5% 30-day move for its own record.\n+44 points — Larger than 96% of 30-day moves · 3,099 observations since Feb 2018.\nFear & Greed moved from Fear to Greed.\nNow 69 · Greed.\nWindow: 30 days · as of 30 Aug 2026\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 35/100 · weekly · since 4 Jul 2026\n· Sentiment: Greed · 69/100 · since 20 Aug 2026\n· ETF demand: 1-day outflow streak · +$1.84B over 7 trading days · as of 28 Aug 2026\n\nSee Fear & Greed in full context → https://halvinglens.com/cycle-dashboard#dashboard-market-board\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-edition-v1"
  },
  {
    "slug": "2026-08-29",
    "subject": "Nothing crossed a line today — all 15 readings held",
    "activity": "active",
    "storyKind": "quiet",
    "text": "HALVINGLENS DAILY BRIEF — 29 Aug 2026\nBTC $77,717 · −3.2% since yesterday's 08:00 London snapshot\n\nTHE VERDICT: Little changed across the 15 monitored readings today. Crowd enthusiasm is heating up while the accumulation window remains open.\n10 of 15 monitored readings held within their own ordinary 7-day ranges — 5 moved materially.\n\nA QUIET DAY: No reading crossed a state boundary, made a top-5% move for its own record, or extended a notable streak today.\nStable readings are information: every standing state below keeps counting, and the day's calm is measured against each reading's own history, not a feeling.\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 35/100 · weekly · since 4 Jul 2026\n· Sentiment: Greed · 68/100 · since 20 Aug 2026\n· ETF demand: 1-day outflow streak · +$1.84B over 7 trading days · as of 28 Aug 2026\n\nSee all 15 signals holding steady → https://halvinglens.com/cycle-dashboard#dashboard-market-board\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-edition-v1"
  },
  {
    "slug": "2026-08-28",
    "subject": "One of Accumulation Index's largest 7-day moves on record.",
    "activity": "active",
    "storyKind": "state_change",
    "text": "HALVINGLENS DAILY BRIEF — 28 Aug 2026\n\nTHE VERDICT: Active week. 3 of 15 monitored readings held within their own ordinary 7-day ranges — 12 moved materially.\n\nA STATE CHANGED: One of Accumulation Index's largest 7-day moves on record. Current reading: 35.\n\nALSO TODAY: RHODL Ratio also moved: +42.9% in 7 days — Larger than 92% of 7-day moves · 1,487 observations since Jul 2022\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 35/100 · weekly · since 4 Jul 2026\n· Sentiment: Greed · 73/100 · since 20 Aug 2026\n· ETF demand: 9-day inflow streak · +$2.56B over 7 trading days · as of 27 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  },
  {
    "slug": "2026-08-27",
    "subject": "A state changed: NUPL",
    "activity": "active",
    "storyKind": "state_change",
    "text": "HALVINGLENS DAILY BRIEF — 27 Aug 2026\n\nTHE VERDICT: Active week. 1 of 15 monitored readings held within their own ordinary 7-day ranges — 14 moved materially.\n\nA STATE CHANGED: NUPL has entered Optimism. Current reading: 0.334.\n\nALSO TODAY: RHODL Ratio also moved: +90.5% in 7 days — Larger than 99% of 7-day moves · 1,486 observations since Jul 2022\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 35/100 · weekly · since 4 Jul 2026\n· Sentiment: Greed · 71/100 · since 20 Aug 2026\n· ETF demand: 8-day inflow streak · +$2.50B over 7 trading days · as of 26 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  },
  {
    "slug": "2026-08-26",
    "subject": "NUPL has entered Optimism.",
    "activity": "active",
    "storyKind": "state_change",
    "text": "HALVINGLENS DAILY BRIEF — 26 Aug 2026\n\nTHE VERDICT: Active week. 2 of 15 monitored readings held within their own ordinary 7-day ranges — 13 moved materially.\n\nA STATE CHANGED: NUPL has entered Optimism. Current reading: 0.330.\n\nALSO TODAY: RHODL Ratio also moved: +72.8% in 7 days — Larger than 98% of 7-day moves · 1,485 observations since Jul 2022\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 35/100 · weekly · since 4 Jul 2026\n· Sentiment: Greed · 65/100 · since 20 Aug 2026\n· ETF demand: 7-day inflow streak · +$2.57B over 7 trading days · as of 25 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  },
  {
    "slug": "2026-08-25",
    "subject": "A state changed: NUPL",
    "activity": "active",
    "storyKind": "state_change",
    "text": "HALVINGLENS DAILY BRIEF — 25 Aug 2026\n\nTHE VERDICT: Active week. 2 of 15 monitored readings held within their own ordinary 7-day ranges — 13 moved materially.\n\nA STATE CHANGED: NUPL has entered Optimism. Current reading: 0.335.\n\nALSO TODAY: MVRV Z-Score also moved: +0.48 points in 7 days — Larger than 98% of 7-day moves · 1,484 observations since Jul 2022\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 35/100 · weekly · since 4 Jul 2026\n· Sentiment: Greed · 74/100 · since 20 Aug 2026\n· ETF demand: 6-day inflow streak · +$2.20B over 7 trading days · as of 24 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  },
  {
    "slug": "2026-08-24",
    "subject": "NUPL has entered Optimism.",
    "activity": "active",
    "storyKind": "state_change",
    "text": "HALVINGLENS DAILY BRIEF — 24 Aug 2026\n\nTHE VERDICT: Active week. 2 of 15 monitored readings held within their own ordinary 7-day ranges — 13 moved materially.\n\nA STATE CHANGED: NUPL has entered Optimism. Current reading: 0.324.\n\nALSO TODAY: Fear & Greed also moved: +42 points in 7 days — Larger than 99% of 7-day moves · 3,116 observations since Feb 2018\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 35/100 · weekly · since 4 Jul 2026\n· Sentiment: Greed · 73/100 · since 20 Aug 2026\n· ETF demand: 5-day inflow streak · +$1.73B over 7 trading days · as of 21 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  },
  {
    "slug": "2026-08-23",
    "subject": "A state changed: NUPL",
    "activity": "active",
    "storyKind": "state_change",
    "text": "HALVINGLENS DAILY BRIEF — 23 Aug 2026\n\nTHE VERDICT: Active week. 3 of 15 monitored readings held within their own ordinary 7-day ranges — 12 moved materially.\n\nA STATE CHANGED: NUPL has entered Optimism. Current reading: 0.319.\n\nALSO TODAY: MVRV Z-Score also moved: +0.50 points in 7 days — Larger than 98% of 7-day moves · 1,482 observations since Jul 2022\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 35/100 · weekly · since 4 Jul 2026\n· Sentiment: Greed · 66/100 · since 20 Aug 2026\n· ETF demand: 5-day inflow streak · +$1.73B over 7 trading days · as of 21 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  },
  {
    "slug": "2026-08-22",
    "subject": "NUPL has entered Optimism.",
    "activity": "active",
    "storyKind": "state_change",
    "text": "HALVINGLENS DAILY BRIEF — 22 Aug 2026\n\nTHE VERDICT: Active week. 4 of 15 monitored readings held within their own ordinary 7-day ranges — 11 moved materially.\n\nA STATE CHANGED: NUPL has entered Optimism. Current reading: 0.331.\n\nALSO TODAY: Reserve Risk also moved: +23.8% in 7 days — Larger than 98% of 7-day moves · 1,481 observations since Jul 2022\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 22/100 · weekly · since 4 Jul 2026\n· Sentiment: Greed · 71/100 · since 20 Aug 2026\n· ETF demand: 5-day inflow streak · +$1.73B over 7 trading days · as of 21 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  },
  {
    "slug": "2026-08-21",
    "subject": "A state changed: NUPL",
    "activity": "active",
    "storyKind": "state_change",
    "text": "HALVINGLENS DAILY BRIEF — 21 Aug 2026\n\nTHE VERDICT: Active week. 3 of 15 monitored readings held within their own ordinary 7-day ranges — 12 moved materially.\n\nA STATE CHANGED: NUPL has entered Optimism. Current reading: 0.285.\n\nALSO TODAY: Fear & Greed also moved: +43 points in 7 days — Larger than 99% of 7-day moves · 3,113 observations since Feb 2018\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 22/100 · weekly · since 4 Jul 2026\n· Sentiment: Greed · 72/100 · since 20 Aug 2026\n· ETF demand: 4-day inflow streak · +$1.36B over 7 trading days · as of 20 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  },
  {
    "slug": "2026-08-20",
    "subject": "A state changed: NUPL",
    "activity": "active",
    "storyKind": "state_change",
    "text": "HALVINGLENS DAILY BRIEF — 20 Aug 2026\n\nTHE VERDICT: Active week. 6 of 15 monitored readings held within their own ordinary 7-day ranges — 9 moved materially.\n\nA STATE CHANGED: One of NUPL's largest 24-hour moves on record. Current reading: 0.245.\n\nALSO TODAY: Fear & Greed also moved: +33 points in 7 days — Larger than 97% of 7-day moves · 3,112 observations since Feb 2018\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 22/100 · weekly · since 4 Jul 2026\n· Sentiment: Greed · 62/100 · since 20 Aug 2026\n· ETF demand: 3-day inflow streak · +$759.01M over 7 trading days · as of 19 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  },
  {
    "slug": "2026-08-19",
    "subject": "A state changed: Fear & Greed",
    "activity": "active",
    "storyKind": "state_change",
    "text": "HALVINGLENS DAILY BRIEF — 19 Aug 2026\n\nTHE VERDICT: Active week. 12 of 15 monitored readings held within their own ordinary 7-day ranges — 3 moved materially.\n\nA STATE CHANGED: Fear & Greed has entered Neutral. Current reading: 46.\n\nALSO TODAY: ETF demand: 2 straight trading days of net inflows. Net +$97.14M over the past 7 trading days.\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 22/100 · weekly · since 4 Jul 2026\n· Sentiment: Neutral · 46/100 · since 19 Aug 2026\n· ETF demand: 2-day inflow streak · +$97.14M over 7 trading days · as of 18 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  },
  {
    "slug": "2026-08-18",
    "subject": "Market Price just made an unusual move",
    "activity": "active",
    "storyKind": "mover",
    "text": "HALVINGLENS DAILY BRIEF — 18 Aug 2026\n\nTHE VERDICT: Active week. 11 of 15 monitored readings held within their own ordinary 7-day ranges — 4 moved materially.\n\nSOMETHING CHANGED: Market Price — +0.82% in 7 days · Unusual.\nMarket Price moved from above to below the estimated mining cost. Larger than 10% of 7-day moves · 5,868 observations since Jul 2010.\nNow $64,434 · −0.53% over 30 days.\n\nALSO TODAY: SOPR is approaching its Mild profit range.\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 22/100 · weekly · since 4 Jul 2026\n· Sentiment: Fear · 41/100 · since 15 Jul 2026\n· ETF demand: 3-day outflow streak · −$162.18M over 7 trading days · as of 14 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  },
  {
    "slug": "2026-08-17",
    "subject": "RHODL Ratio: −29.4% in 7 days — unusual by its own record",
    "activity": "active",
    "storyKind": "mover",
    "text": "HALVINGLENS DAILY BRIEF — 17 Aug 2026\n\nTHE VERDICT: Active week. 12 of 15 monitored readings held within their own ordinary 7-day ranges — 3 moved materially.\n\nSOMETHING CHANGED: RHODL Ratio — −29.4% in 7 days · Unusual.\nA larger 7-day move than most in its own record. Larger than 80% of 7-day moves · 1,476 observations since Jul 2022.\nNow 696 · Deep value · −40.3% over 30 days.\n\nALSO TODAY: Market Price also moved: −3.16% in 7 days — Larger than 36% of 7-day moves · 5,867 observations since Jul 2010\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 22/100 · weekly · since 4 Jul 2026\n· Sentiment: Fear · 31/100 · since 15 Jul 2026\n· ETF demand: 3-day outflow streak · −$162.18M over 7 trading days · as of 14 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  },
  {
    "slug": "2026-08-16",
    "subject": "An unusual 7-day move in RHODL Ratio",
    "activity": "active",
    "storyKind": "mover",
    "text": "HALVINGLENS DAILY BRIEF — 16 Aug 2026\n\nTHE VERDICT: Active week. 14 of 15 monitored readings held within their own ordinary 7-day ranges — 1 moved materially.\n\nSOMETHING CHANGED: RHODL Ratio — −31.8% in 7 days · Unusual.\nA larger 7-day move than most in its own record. Larger than 83% of 7-day moves · 1,475 observations since Jul 2022.\nNow 726 · Deep value · −38.4% over 30 days.\n\nALSO TODAY: ETF demand: 3 straight trading days of net outflows. Net −$162.18M over the past 7 trading days.\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 22/100 · weekly · since 4 Jul 2026\n· Sentiment: Fear · 34/100 · since 15 Jul 2026\n· ETF demand: 3-day outflow streak · −$162.18M over 7 trading days · as of 14 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  },
  {
    "slug": "2026-08-15",
    "subject": "RHODL Ratio just made an unusual move",
    "activity": "active",
    "storyKind": "mover",
    "text": "HALVINGLENS DAILY BRIEF — 15 Aug 2026\n\nTHE VERDICT: Active week. 14 of 15 monitored readings held within their own ordinary 7-day ranges — 1 moved materially.\n\nSOMETHING CHANGED: RHODL Ratio — −32.5% in 7 days · Unusual.\nA larger 7-day move than most in its own record. Larger than 84% of 7-day moves · 1,474 observations since Jul 2022.\nNow 713 · Deep value · −37.0% over 30 days.\n\nALSO TODAY: ETF demand: 3 straight trading days of net outflows. Net −$162.18M over the past 7 trading days.\n\nSTATE OF THE CYCLE\n· Accumulation: Historically Attractive · 24/100 · weekly · since 4 Jul 2026\n· Sentiment: Fear · 34/100 · since 15 Jul 2026\n· ETF demand: 3-day outflow streak · −$162.18M over 7 trading days · as of 14 Aug 2026\n\nSee the whole picture: Open the Cycle Dashboard → https://halvinglens.com/cycle-dashboard\n\nWhat would make this Brief more useful? Reply and tell us.\nHistorical context, not a prediction. Educational analysis, not financial advice.",
    "version": "brief-intel-v1"
  }
];
