// AUTO-GENERATED by the daily sync (scripts/persist-brief.ts).
// Each entry is a self-contained snapshot of that day's brief, so dated
// permalinks render real history rather than today's live data.
// New days are appended; do not edit by hand.
import type { StoredBrief } from "../brief";

export const STORED_BRIEFS: StoredBrief[] = [
  {
    "slug": "2026-05-31",
    "dateLabel": "31 May 2026",
    "generatedAt": "2026-05-31T06:46:51.085Z",
    "headline": "Later by time, cooler by price: Bitcoin continues to diverge from prior cycles.",
    "phaseLabel": "Later-running mid-cycle expansion",
    "heat": "neutral",
    "price": 73731.481134,
    "changePct": 0.557242,
    "changeLabel": "24h",
    "cycleDay": 772,
    "progressPct": 53,
    "gainFromHalving": 14.993521999589298,
    "drawdownFromAth": -40.07027605951845,
    "summary": "Bitcoin is later in the cycle by calendar timing, but cooler than previous cycles by price behaviour.",
    "support": "Historically, two of the three previous cycles had already reached their major peak by this point after the halving. The current cycle is behaving differently — flatter and slower, and potentially more structurally supported by ETF demand. This does not guarantee future upside, but it does suggest the current cycle is not following the classic four-year rhythm cleanly.",
    "whatsDifferent": "The 2024 cycle is the first Bitcoin cycle with US spot ETF demand — a structural source of buying that did not exist in 2012, 2016 or 2020. That makes comparison with prior cycles useful, but not perfect. So far this cycle has been flatter and slower than the classic four-year rhythm.",
    "whatToWatch": "Whether price begins to accelerate toward prior-cycle behaviour, plus ETFs have seen net outflows recently, and sentiment is fear. These are the signals that would show the cycle either converging with history or continuing to diverge.",
    "conclusion": "Historically, two of the three previous cycles had already reached their major peak by this point after the halving. The current cycle is behaving differently — flatter and slower, and potentially more structurally supported by ETF demand. This does not guarantee future upside, but it does suggest the current cycle is not following the classic four-year rhythm cleanly.",
    "insights": [
      {
        "title": "Cycle insight of the day",
        "body": "Historically, two of the three previous cycles had already reached their major peak by this point after the halving. The current cycle is behaving differently — flatter and slower, and potentially more structurally supported by ETF demand. This does not guarantee future upside, but it does suggest the current cycle is not following the classic four-year rhythm cleanly."
      },
      {
        "title": "ETF insight of the day",
        "body": "US spot Bitcoin ETFs have seen net outflows over the past week (~$1.70B). Cumulative net flow since launch stands at $19.86B, with the largest single inflow day at $1.21B. ETF demand is the structural variable unique to this cycle."
      },
      {
        "title": "Sentiment insight of the day",
        "body": "Market mood reads fear (Fear & Greed 28/100), flat over the past month. Extremes matter most: euphoria has often appeared near cycle tops, deep fear near lows — a contrarian read, not a timing tool."
      }
    ],
    "watchSignals": [
      {
        "signal": "Divergence from historical cycle timing",
        "status": "Diverging — later by time, cooler by price than prior cycles",
        "level": "watch",
        "confidence": "high"
      },
      {
        "signal": "ETF inflows accelerating",
        "status": "Net outflows of ~$1.7B over the last 7 days",
        "level": "watch",
        "confidence": "high"
      },
      {
        "signal": "Price acceleration vs previous cycles",
        "status": "Steady — -3.0% over the last 7d",
        "level": "calm",
        "confidence": "medium"
      },
      {
        "signal": "Sentiment approaching euphoric territory",
        "status": "Measured — Fear & Greed at 28, flat over 30d",
        "level": "calm",
        "confidence": "high"
      },
      {
        "signal": "Rising risk / heat level",
        "status": "Currently neutral",
        "level": "calm",
        "confidence": "medium"
      },
      {
        "signal": "Miner stress",
        "status": "Miner revenue suppressed, hashrate 1007 EH/s",
        "level": "calm",
        "confidence": "medium"
      }
    ],
    "shortPost": "Bitcoin Cycle Brief:\n\nBTC $73,731.48 (+0.6% 24h) · day 772 of the halving cycle (53% through).\n\nBitcoin is later in the cycle by calendar timing, but cooler than previous cycles by price behaviour.\n\nAt this point, prior cycles had usually already peaked. This cycle is different: slower, flatter, and ETF-supported.\n\nHistorical context, not financial advice.\nhalving.lens"
  }
];
