// AUTO-GENERATED by the daily sync (scripts/persist-edition.ts).
// Each entry is a permanent, self-contained snapshot of that day's Daily
// Research Brief, so /research/<n> renders the exact market conditions from that
// morning — forever. New editions are appended; do not edit by hand.
import type { Edition } from "../research";

export const EDITIONS: Edition[] = [
  {
    "edition": 393,
    "slug": "2026-06-28",
    "dateLabel": "Sunday 28 June 2026",
    "feature": {
      "key": "weekahead",
      "day": "Sunday",
      "title": "Week Ahead"
    },
    "subject": "The crowd is fearful. History wasn't.",
    "take": "Bitcoin remains historically cheap while sentiment sits in extreme fear.",
    "contextScore": {
      "score": 78,
      "label": "Clear historical context",
      "stars": 4
    },
    "oneThing": "Bitcoin is trading within the cheapest 84% of historical weeks, while sentiment remains in extreme fear. We have only seen conditions like this a handful of times before.",
    "confidence": {
      "level": "HIGH",
      "blurb": "Today's data strongly aligns with historical behaviour.",
      "detail": "Valuation, sentiment, cycle timing point the same way; ETF flows diverge."
    },
    "marketHealth": [
      {
        "label": "Historical value",
        "value": "Deep Value",
        "color": "#5fd0a0",
        "strength": 3
      },
      {
        "label": "Sentiment",
        "value": "Extreme fear",
        "color": "#e8786f",
        "strength": 3
      },
      {
        "label": "Cycle position",
        "value": "Cooling",
        "color": "#5fd0a0",
        "strength": 3
      },
      {
        "label": "ETF demand",
        "value": "Weak",
        "color": "#e8786f",
        "strength": 2
      },
      {
        "label": "Momentum",
        "value": "Neutral",
        "color": "#8c919c",
        "strength": 1
      }
    ],
    "historicalContext": {
      "match": "Aug 2022",
      "similarity": 87,
      "body": "Today most closely resembles Aug 2022. The resemblance isn't the date — it's the setup: a similar position in the cycle, a comparable drawdown from the high, and a deep value valuation backdrop, with sentiment in extreme fear. What followed then is context, not a forecast."
    },
    "whyToday": "If history rhymes, today deserves attention — not because it predicts tomorrow, but because environments this cheap have historically been uncommon.",
    "analyst": {
      "quote": "The week ahead matters less than the environment we enter it from.",
      "body": "Forecasts age badly; environments don't. The useful question on a Sunday isn't what happens next, but what kind of market we're standing in — and today that's a deep value one by historical standards. Position is context; the calendar is noise."
    },
    "watching": [
      {
        "signal": "Divergence from historical cycle timing",
        "status": "Diverging — later by time, cooler by price than prior cycles"
      },
      {
        "signal": "ETF inflows accelerating",
        "status": "Net outflows of ~$2.0B over the last 7 days"
      },
      {
        "signal": "Sentiment approaching euphoric territory",
        "status": "Deep fear — Fear & Greed at 18"
      }
    ],
    "memory": "There will only ever be 21 million bitcoin, and more than 19.5 million already exist.",
    "heroNarrative": "similar",
    "readMin": 2,
    "metrics": {
      "price": 59955.56602,
      "fearGreed": 18,
      "accumulationScore": 17,
      "accumulationBand": "Historically Deep Value",
      "accumulationPercentile": 16,
      "cycleDay": 800,
      "etf": "Weak",
      "sentiment": "Extreme fear"
    },
    "search": "bitcoin remains historically cheap while sentiment sits in extreme fear. bitcoin is trading within the cheapest 84% of historical weeks, while sentiment remains in extreme fear. we have only seen conditions like this a handful of times before. the week ahead matters less than the environment we enter it from. forecasts age badly; environments don't. the useful question on a sunday isn't what happens next, but what kind of market we're standing in — and today that's a deep value one by historical standards. position is context; the calendar is noise. today most closely resembles aug 2022. the resemblance isn't the date — it's the setup: a similar position in the cycle, a comparable drawdown from the high, and a deep value valuation backdrop, with sentiment in extreme fear. what followed then is context, not a forecast. if history rhymes, today deserves attention — not because it predicts tomorrow, but because environments this cheap have historically been uncommon. there will only ever be 21 million bitcoin, and more than 19.5 million already exist. week ahead clear historical context extreme fear historically deep value divergence from historical cycle timing diverging — later by time, cooler by price than prior cycles etf inflows accelerating net outflows of ~$2.0b over the last 7 days sentiment approaching euphoric territory deep fear — fear & greed at 18"
  }
];
